name: CI

on:
  push:
    branches: [master, next, github-action]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #,windows-latest]
        os: [ubuntu-latest, macos-latest]
        node: [6, 12]

    steps:
      - uses: actions/checkout@v2
      # powershell is already install on GitHub-hosted runners
      # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci || npm i
      - run: npm run ci
